package org.kendar;// Generated by Selenium IDE

import org.kendar.globaltest.Sleeper;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.kendar.SeleniumBase.*;

public class GoogleHackSetupTest {

    public static void verify(ChromeDriver driver) throws InterruptedException {


        driver.get("https://www.google.com");
        Sleeper.sleep(2000);
        setupSize(driver);
        Sleeper.sleep(1000);
        acceptCookies(driver);
        Sleeper.sleep(3000);
        var text = driver.executeScript("return document.documentElement.outerHTML;").toString();
        assertTrue(text.contains("Bing_logo"));
    }


    public static void setup(ChromeDriver driver) throws InterruptedException {
        driver.get("https://www.google.com");

        Sleeper.sleep(2000);
        acceptCookies(driver);
        Sleeper.sleep(3000);
        var text = driver.executeScript("return document.documentElement.outerHTML;").toString();
        assertFalse(text.contains("Bing_logo"));
        driver.get("http://www.local.test/index.html");
        Sleeper.sleep(1000);
        setupSize(driver);
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("grid-rowc-2-0")));
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("ssl-sites-add")));
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("address")));
        driver.findElement(By.id("address")).sendKeys("www.google.com");
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("address")));
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("mod-save")));
//    Sleeper.sleep(1000);
//    try {
//doClick(()->driver.findElement(By.id("mod-save")));
//    }catch (Exception e){}
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.linkText("Main")));
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("grid-rowc-0-0")));
        Sleeper.sleep(1000);

        doClick(() -> driver.findElement(By.linkText("MAPPINGS")));
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("dns-mappings-add")));
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("dns")));
        Sleeper.sleep(1000);
        driver.findElement(By.id("dns")).sendKeys("www.google.com");
        Sleeper.sleep(1000);

        doClick(() -> driver.findElement(By.id("mod-save")));
//    try {
//doClick(()->driver.findElement(By.id("mod-save")));
//    }catch (Exception ex){}
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.linkText("Main")));
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.linkText("JsFilter web")));
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("js-grid-addnew")));
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("createScriptName")));
        Sleeper.sleep(1000);
        driver.findElement(By.id("createScriptName")).sendKeys("GoogleHack");
        Sleeper.sleep(1000);

        doClick(() -> driver.findElement(By.id("createScriptBt")));
//    try{
//
//doClick(()->driver.findElement(By.id("createScriptBt")));
//    }catch (Exception ex){}
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("grid-rowe-0-0")));
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.linkText("CURRENT")));
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("phase")));
        Sleeper.sleep(1000);
        {
            WebElement dropdown = driver.findElement(By.id("phase"));
            dropdown.findElement(By.xpath("//option[. = 'POST_CALL']")).click();
        }
        Sleeper.sleep(1000);
        driver.findElement(By.cssSelector("#phase > option:nth-child(6)")).click();
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("hostAddress")));
        Sleeper.sleep(1000);
        driver.findElement(By.id("hostAddress")).clear();
        driver.findElement(By.id("hostAddress")).sendKeys("www.google.com");
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("pathAddress")));
        Sleeper.sleep(1000);
        driver.findElement(By.id("pathAddress")).clear();
        driver.findElement(By.id("pathAddress")).sendKeys("/");
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("source")));
        Sleeper.sleep(1000);
        driver.findElement(By.id("source")).clear();
        //driver.findElement(By.id("source")).sendKeys("var regex=/\\/images\\/branding\\/[_a-zA-Z0-9]+\\/[_a-zA-Z0-9]+\\/[_a-zA-Z0-9]+\\.png/gm;\\nvar responseText = response.getResponseText()+\"\";\\nvar changedText = responseText.replace(regex,\'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Bing_logo_%282016%29.svg/320px-Bing_logo_%282016%29.svg.png\');\\nresponse.setResponseText(changedText);\\nreturn false;");
        driver.findElement(By.id("source")).sendKeys("var regex=/\\/images\\/branding\\/[_a-zA-Z0-9]+\\/[_a-zA-Z0-9]+\\/[_a-zA-Z0-9]+\\.png/gm;\n" +
                "var responseText = response.getResponseText()+\"\";\n" +
                "var changedText = responseText.replace(regex,'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Bing_logo_%282016%29.svg/320px-Bing_logo_%282016%29.svg.png');\n" +
                "response.setResponseText(changedText);\n" +
                "return false;");
        Sleeper.sleep(1000);
        doClick(() -> driver.findElement(By.id("editfilter-save")));
        Sleeper.sleep(1000);
    }

    private static void acceptCookies(ChromeDriver driver) {
        try {
            WebElement el = null;
            try {
                el = scrollFind(driver, () -> driver.findElement(By.xpath("//*[text()='Accetta tutto']")));
            }catch (Exception e){

            }
            if (el == null) {
                el = scrollFind(driver,()-> driver.findElement(By.xpath("//*[text()='Accept all']")));
            }
            el.click();
        }catch (Exception ex){

        }
    }
}
