version: "3.2"
networks:
  sampleappnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.8.0/24
services:
  ham.sampleapp.single.openvpn:
    container_name: ham.sampleapp.single.openvpn
    privileged: true
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    dns:
      - 127.0.0.1
    ports:
      - target: 3000
        published: 1194
        protocol: udp
    networks:
      sampleappnet: {}
    environment:
      - DNS_HIJACK_SERVER=ham.sampleapp.single.master
      - ROOT_PWD=root
    image: ham.openvpn
    depends_on:
      ham.sampleapp.single.master:
        condition: service_healthy
  ham.sampleapp.single.master:
    container_name: ham.sampleapp.single.master
    privileged: true
    environment:
      - ROOT_PWD=root
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    dns:
      - 127.0.0.1
    image: ham.sampleapp.single
    networks:
      sampleappnet: {}
    ports:
      - target: 1080
        published: 1080
      - target: 1081
        published: 1081
      - target: 5025
        published: 5025