version: "2"
networks:
  masternet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.1.0/24
services:
  ham.master.openvpn:
    container_name: ham.master.openvpn
    privileged: true
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    ports:
      - "3000:1194/udp"
    networks:
      - masternet
    environment:
      - DNS_HIJACK_SERVER=ham.master.master
      - ROOT_PWD=root
    image: ham.openvpn
    depends_on:
      - ham.master.master
  ham.master.master:
    container_name: ham.master.master
    privileged: true
    environment:
      - ROOT_PWD=root
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    dns:
      - 127.0.0.1
    image: ham.master.master
    networks:
      - masternet