version: "3.2"
networks:
  multisampleappnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.7.0/24
services:
  ham.sampleapp.multi.openvpn:
    container_name: ham.sampleapp.multi.openvpn
    privileged: true
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    dns:
      - 127.0.0.1
    ports:
      - target: 3000
        published: 1194
        protocol: udp
    networks:
      multisampleappnet: {}
    environment:
      - DNS_HIJACK_SERVER=ham.sampleapp.multi.master
      - ROOT_PWD=root
    image: kendarorg/ham.openvpn:latest
    depends_on:
      ham.sampleapp.multi.master:
        condition: service_healthy
  ham.sampleapp.multi.master:
    container_name: ham.sampleapp.multi.master
    privileged: true
    environment:
      - ROOT_PWD=root
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    dns:
      - 127.0.0.1
    image: kendarorg/ham.sampleapp.multi:latest
    networks:
      multisampleappnet: {}
    ports:
      - target: 1080
        published: 1080
      - target: 1081
        published: 1081
      - target: 5025
        published: 5025
  ham.sampleapp.multi.gateway:
    container_name: gateway.sample.test
    privileged: true
    environment:
      - DNS_HIJACK_SERVER=ham.sampleapp.multi.master
      - ROOT_PWD=root
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    dns:
      - 127.0.0.1
    image: kendarorg/ham.sampleapp.gateway:latest
    networks:
      multisampleappnet: {}
    depends_on:
      ham.sampleapp.multi.master:
        condition: service_healthy
  ham.sampleapp.multi.be:
    container_name: be.sample.test
    privileged: true
    environment:
      - DNS_HIJACK_SERVER=ham.sampleapp.multi.master
      - ROOT_PWD=root
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    dns:
      - 127.0.0.1
    image: kendarorg/ham.sampleapp.be:latest
    networks:
      multisampleappnet: {}
    depends_on:
      ham.sampleapp.multi.master:
        condition: service_healthy

  ham.sampleapp.multi.fe:
    container_name: www.sample.test
    privileged: true
    environment:
      - DNS_HIJACK_SERVER=ham.sampleapp.multi.master
      - ROOT_PWD=root
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    dns:
      - 127.0.0.1
    image: kendarorg/ham.sampleapp.fe:latest
    networks:
      multisampleappnet: {}
    depends_on:
      ham.sampleapp.multi.master:
        condition: service_healthy