version: "2"
networks:
  multisampleappnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.3.0/24
services:
  ham.sampleapp.multi.openvpn:
    container_name: ham.sampleapp.multi.openvpn
    privileged: true
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    dns:
      - 127.0.0.1
    ports:
      - "3000:1194/udp"
    networks:
      - multisampleappnet
    environment:
      - DNS_HIJACK_SERVER=ham.sampleapp.multi.master
      - ROOT_PWD=root
    image: kendarorg/ham.openvpn:latest
    depends_on:
      - ham.sampleapp.multi.master
  ham.sampleapp.multi.master:
    container_name: ham.sampleapp.multi.master
    privileged: true
    environment:
      - ROOT_PWD=root
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    dns:
      - 127.0.0.1
    image: kendarorg/ham.sampleapp.multi:latest
    networks:
      - multisampleappnet
    ports:
      - "5025:5025"
      - "1080:1080"
  ham.sampleapp.multi.gateway:
    container_name: gateway.sample.test
    privileged: true
    environment:
      - DNS_HIJACK_SERVER=ham.sampleapp.multi.master
      - ROOT_PWD=root
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    dns:
      - 127.0.0.1
    image: kendarorg/ham.sampleapp.gateway:latest
    networks:
      - multisampleappnet
    depends_on:
      - ham.sampleapp.multi.master
  ham.sampleapp.multi.be:
    container_name: be.sample.test
    privileged: true
    environment:
      - DNS_HIJACK_SERVER=ham.sampleapp.multi.master
      - ROOT_PWD=root
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    dns:
      - 127.0.0.1
    image: kendarorg/ham.sampleapp.be:latest
    networks:
      - multisampleappnet
    depends_on:
      - ham.sampleapp.multi.master
  ham.sampleapp.multi.fe:
    container_name: www.sample.test
    privileged: true
    environment:
      - DNS_HIJACK_SERVER=ham.sampleapp.multi.master
      - ROOT_PWD=root
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    dns:
      - 127.0.0.1
    image: kendarorg/ham.sampleapp.fe:latest
    networks:
      - multisampleappnet
    depends_on:
      - ham.sampleapp.multi.master