version: "2"
networks:
  vpnnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.8.0/24
services:
  ham.vpn.openvpn:
    container_name: ham.vpn.openvpn
    privileged: true
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    ports:
      - "3000:1194/udp"
    networks:
      - vpnnet
    image: ham.openvpn
    environment:
      - ROOT_PWD=root
  ham.vpn.forticlient:
    container_name: ham.vpn.forticlient
    privileged: true
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    networks:
      - vpnnet
    image: ham.forticlient
    environment:
      - ROOT_PWD=root
  ham.vpn.openconnect:
    container_name: ham.vpn.openconnect
    privileged: true
    cap_add:
      - NET_ADMIN
      - DAC_READ_SEARCH
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    networks:
      - vpnnet
    image: ham.openconnect
    environment:
      - ROOT_PWD=root